name: Gordian Open Integrity

on: [push, pull_request]

jobs:
  gordian-open-integrity:
    name: Gordian Open Integrity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Stream44/t44-blockchaincommons.com@main
